#!/usr/bin/env bash
# Bash script that installs Nginx server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
