#!/bin/bash
# Update the package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start

# Add redirection rule
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://github.com/mohamad-samir;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart
