#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Create a PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM and SIGQUIT signals
quit_term_handler(){
  echo "I hate the kill command"
  rm /var/run/myscript.pid
  exit 0
}

# Function to handle SIGINT signal
int_handler(){
  echo "Y U no love me?!"
}

# Trap signals and call respective handler functions
trap 'quit_term_handler' SIGQUIT SIGTERM
trap 'int_handler' SIGINT

# Loop indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 1
done
