#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Get the PID of the current process
pid=$(echo $$)

# Create the PID file
echo $pid > /var/run/myscript.pid

# Loop indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done

# Handle SIGINT and SIGQUIT signals
trap 'echo "Y U no love me?!"; exit' INT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' QUIT SIGTERM
