#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process
PIDFILE=/var/run/my_process.pid
case "\$1" in 
  start)
    nohup ./manage_my_process >/dev/null 2>&1 &
    echo $! > $PIDFILE
    echo "manage_my_process started"
    ;;
  stop)
    kill `cat $PIDFILE`
    rm $PIDFILE
    echo "manage_my_process stopped"
    ;;
  restart)
    kill `cat $PIDFILE`
    rm $PIDFILE
    nohup ./manage_my_process >/dev/null 2>&1 &
    echo $! > $PIDFILE
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: \$0 {start|stop|restart}"
    exit 1
esac
