#!/usr/bin/env bash
# This script displays a string infinitely with a 2-second delay between each iteration.
# It catches a SIGTERM signal and displays a text.

# Function to handle SIGTERM signal
term_handler(){
  echo "I am invincible!!!"
}

# Trap SIGTERM signal and call term_handler function when that happens
trap 'term_handler' SIGTERM

# Loop indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
