#!/usr/bin/env bash
# This script displays "Best School" 10 times (but prints something extra on the 9th iteration) using a while loop and an if statement
counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
