#!/bin/bash

# Install ufw if not already installed
sudo apt-get install ufw -y

# Enable ufw
sudo ufw enable

# Allow SSH, HTTPS, and HTTP traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Block all other incoming traffic
sudo ufw default deny incoming

# Display ufw status
sudo ufw status

echo "UFW configuration completed."

# Exit the script
exit 0
